### ISSUE TITLE
excellent multilingual implementation

### ISSUE THREAD

**Issue by emlog** [codersclub/emlog.ml#1]
emlog core want to support multiple languages, and wants to merge your multilingual implementation parts to the emlog core. I hope to get your consent and support.

**Comment by codersclub** [comment]
I am very glad that after 9 years you have paid attention to my modest efforts to turn Emlog into an international project! :)
Applying multilingual changes to the Emlog core is very easy. I purposely kept my master branch as an exact copy of the original Emlog branch. All multilingual modifications are placed in a separate "multilang" branch. To enable multilingualism in the core, it is enough to merge my "multilang" branch into your master branch.

**Comment by emlog** [comment]
I'm sorry that I'm starting to pay attention to internationalization now, but it's not too late, it has been merged into the core, and I will make some adjustments, and I hope you can  submit pr  to the core in the future.thank u  vervy much.

**Comment by codersclub** [comment]
Yes, of course, I'll do everything in my power to make Emlog even better!

**Comment by emlog** [comment]
Based on your multilingual version, I created a new independent official multilingual version warehouse (https://github.com/emlog/emlog-ml), and no longer use the original method of different branches. I built on this with some bug fixes and minor tweaks. And released version 2.1.8 on emlog.io, I hope we can maintain the official https://github.com/emlog/emlog-ml warehouse together, of course I don’t know if this is bad, but I really need one Independent official multilingual repository. Hope you can support this.

**Comment by emlog** [comment]
I didn't add Russian because I really don't understand Russian and can't maintain it, and I'm not sure if you are interested in supporting this official multilingual version.

**Comment by codersclub** [comment]
I agree to support the official multilingual version with you.
For further joint work, we need to create and agree on the rules of our interaction.
